name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install backend deps
        working-directory: ./services/api
        run: npm ci
        
      - name: Run Backend Tests
        working-directory: ./services/api
        run: npm run test
        
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          
      - name: Get mobile dependencies
        working-directory: ./apps/mobile
        run: flutter pub get
        
      - name: Flutter Analyze
        working-directory: ./apps/mobile
        run: flutter analyze
        
      - name: Flutter Test
        working-directory: ./apps/mobile
        run: flutter test
