name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.x'
        channel: 'stable'
        architecture: x64
        
    - name: Generate Native Platforms
      working-directory: ./apps/mobile
      run: flutter create --platforms=ios .

    - name: Get dependencies
      working-directory: ./apps/mobile
      run: flutter pub get

    - name: Fix iOS Minimum Deployment Target
      working-directory: ./apps/mobile/ios
      run: sed -i '' "s/^# platform :ios.*/platform :ios, '13.0'/g" Podfile
      
    - name: Build iOS App (No Sign)
      working-directory: ./apps/mobile
      run: flutter build ios --release --no-codesign

    - name: Package IPA
      working-directory: ./apps/mobile
      run: |
        mkdir -p Payload
        mv build/ios/iphoneos/Runner.app Payload/
        zip -r -qq DARB_iOS.ipa Payload

    - name: Upload iOS IPA
      uses: actions/upload-artifact@v3
      with:
        name: DARB-iOS-App
        path: ./apps/mobile/DARB_iOS.ipa
